#! /usr/bin/env ruby

require 'net/http'
require 'base64'

HTTP_OK    = "200"
HTTP_ERROR = "500"
BLOCK_SIZE = 16
BYTE_RANGE = (0..255).to_a
blocks = Base64.decode64(ARGV[0]).bytes.each_slice(16).map(&:to_a)

def send_request(cookie)
  url = "http://localhost:4555"
  uri = URI(url)
  http = Net::HTTP.new(uri.host, 4555)
  request = Net::HTTP::Get.new(uri.request_uri)
  request['Cookie'] = "user=#{cookie}"
  http.request(request)
end

def find_offset(test_block, decrypt_block, pos)
  (BYTE_RANGE).detect do |v|
    test_block[pos] = v
    guess = Base64.encode64((test_block + decrypt_block).pack('c*'))
    res = send_request(guess)
    res.code == HTTP_OK
  end
end

def calculate_padding(test_block, decrypt_block)
  BLOCK_SIZE - BLOCK_SIZE.times.detect do |i|
    test_block[i] ^= 1
    guess = Base64.encode64((test_block + decrypt_block).pack('c*'))
    res = send_request(guess)
    res.code == HTTP_ERROR
  end
end

def decrypt(decrypt_block, cipher_block)
  hack_block = BYTE_RANGE.shuffle.first(16)
  encoded_bytes = Array.new(BLOCK_SIZE, 0)
  padding_length = 0

  decrypt_block.reverse.each_with_index do |byte, index|
    pos = BLOCK_SIZE - index - 1
    if index.zero?
      hack_block[pos] = find_offset(hack_block.dup, decrypt_block, pos)
      padding_length = calculate_padding(hack_block.dup, decrypt_block)
      encoded_bytes[pos] = hack_block[pos] ^ padding_length
    elsif index < padding_length - 1
      encoded_bytes[pos] = hack_block[pos]
    else
      hack_block[BLOCK_SIZE - 1] = encoded_bytes.last ^ (index + 1)
      encoded_bytes[pos] = hack_block[pos] = find_offset(hack_block.dup, decrypt_block, pos)
    end
  end

  decrypted_text = cipher_block.zip(encoded_bytes).map do |cipher_byte, encoded_byte|
    cipher_byte ^ encoded_byte
  end.pack("c*")

  {
    :text => decrypted_text,
    :padding => padding_length
  }
end

decrypted_block = decrypt(blocks.pop, blocks.last)
decrypted_message = decrypted_block[:text]
padding = decrypted_block[:padding]

decrypted_message = (blocks.length - 1).times.inject("") do |acc, i|
  decrypt(blocks.pop, blocks.last)[:text] + acc
end + decrypted_message

puts decrypted_message[0...(padding * -1)]
