#!/usr/bin/env ruby

require 'packetfu'
require 'pry'
require 'resolv'
require_relative 'attack'
require_relative 'anomaly'
require_relative 'spoof'
require_relative 'server'
require_relative 'sinkhole'
require_relative 'arp'
require_relative 'unicode'
require_relative 'ddos'

include PacketFu

# The CIDR format 10.0.0.0/8 translates to the range 10.0.0.0 to 10.255.255.0
MIN_ADDRESS = 167772160.freeze                                                  # min IP of 10.0.0.0 to decimal
MAX_ADDRESS = 184549375.freeze                                                  # max IP of 10.255.255.0 to decimal
PATH = ARGV[0]
exit if PATH.nil?

args = {
  min_addr: MIN_ADDRESS,
  max_addr: MAX_ADDRESS
}

anomaly = Anomaly.new(args)
spoof = Spoof.new(args.merge!({ type: 'Spoofed IP address' }))
server = Server.new(args.merge!({
    attempted_type: 'Attempted server connection',
    accepted_type: 'Accepted server connection'
}))
sinkhole = Sinkhole.new(args.merge!({
  type: 'Sinkhole lookup',
  sinkholes_path: 'sinkholes.txt'
}))
arp = Arp.new(args.merge!({
  type: 'Potential ARP spoofing'
}))
unicode = Unicode.new(args.merge!({
    type: 'Unicode IIS exploit',
    unicode_chars: [
      '%2f',                                                                    # 1-byte encoding of '/'
      '%c0%af',                                                                 # 2-byte encoding of '/'
      '%e0%80%af',                                                              # 3-byte encoding of '/'
      '%f0%80%80%af',                                                           # 4-byte encoding of '/'
      '%f8%80%80%80%af',                                                        # 5-byte encoding of '/'
      '%fc%80%80%80%80%af',                                                     # 6-byte encoding of '/'
      '%5c',                                                                    # 1-byte encoding of '\'
      '%c1%9c',                                                                 # 2-byte encoding of '\'
      '%e0%81%9c',                                                              # 3-byte encoding of '\'
      '%f0%80%81%9c',                                                           # 4-byte encoding of '\'
      '%252f',                                                                  # %25 = %, so we get %2f
      '%255c',                                                                  # %25 = %, so we get %5c
      '%%35c',                                                                  # %35 = 5, so we get %5c
      '%%35%63',                                                                # %63 = c, so we get %5c
      '%25%35%63',                                                              # %25 = %, %35 = 5, %63 = c, get %5c
      '%c1%1c',                                                                 # Invalid UTF-8 but accepted: 11000001 00011100 for the 2-byte instead of valid 11000001 10011100 (%c1%9c)
      '%c0%2f',                                                                 # Invalid UTF-8 but accepted: 11000000 00101111 for the 2-byte instead of valid 11000000 10101111 (%c0%af)
      '%fc%80%80%80%af',                                                        # Invalid UTF-8 but accepted: 11111100 ... instead of 1111100, which would be the valid version for a 5-byte encoding
      '%e0\%80\%af',                                                            # These 2 are unknown
      '%c1%af'
    ]
}))
ddos = DDOS.new(args.merge!({
    type: 'NTP DDoS'
}))

begin
  packets = PcapFile.read_packets(PATH)
rescue ArgumentError
  puts "Could not read packets from file \"#{PATH}\""
  exit
end

packets.each do |packet|
  spoof.run(packet)
  server.run(packet)
  sinkhole.run(packet)
  anomaly.run(packet)
  arp.run(packet)
  unicode.run(packet)
  ddos.run(packet)
end
anomaly.message
